#!/usr/bin/env bash

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

# Info
printinfo () {
    info linebreak
    info linebreak
    info linebreak
    info linebreak
    info linebreak

    prin "$(color 6)OS: $(color 7)OS X"
    info "Shell" shell
    prin "$(color 6)Resolution: $(color 7)2880x1800"
    prin "$(color 6)WM: $(color 7)Kwm"
    info "GPU" gpu
    info "CPU" cpu
    info "Memory" memory

    info linebreak
    info linebreak
}

kernel_shorthand="off"
osx_buildversion="off"
osx_codename="on"
os_arch="off"

uptime_shorthand="on"

shell_path="off"
shell_version="off"

speed_type="max"
cpu_shorthand="tiny"
cpu_display="off"
cpu_cores="off"

gpu_shorthand="on"
refresh_rate="on"

gtk_shorthand="off"
gtk2="off"
gtk3="off"

battery_num="all"
battery_shorthand="on"

public_ip_host="http://ident.me"

song_shorthand="on"

birthday_shorthand="on"
birthday_time="off"
birthday_format="+%a %d %b %Y %l:%M %p"

# Color Blocks
start=0
end=7
color_blocks="on"
block_width=6
colors=(6 1 5 6 6 8)

line_wrap="off"
bold="off"
underline="on"
underline_char="━"
prompt_height=1

progress_char="━"
progress_length="15"
progress_color_elapsed="5"
progress_color_total="6"
memory_display="info"
battery_display="info"
disk_display="info"

image="/Users/Matthew/Dropbox/Wallpapers/Portal_Gun.137.jpg"
thumbnail_dir="$HOME/.cache/thumbnails/neofetch"
w3m_img_path="/usr/lib/w3m/w3mimgdisplay"
image_position="left"
crop_mode="fill"
crop_offset="east"
image_size="auto"
gap=6
yoffset=6
xoffset=6

ascii="distro"
ascii_colors=(2 3 1 1 5 6)
ascii_logo_size="normal"

scrot="off"
scrot_cmd="scrot -c -d 3"
scrot_dir="$HOME/Dropbox/Screenshots/"
scrot_name="neofetch-$(date +%F-%T).png"

stdout_separator="  "

config="on"
config_file="${XDG_CONFIG_HOME:-${HOME}/.config}/neofetch/config"
